### ISSUE TITLE
Cron container update: exception

### ISSUE THREAD

**Issue by brightdroid** [dockupdater/dockupdater#29]
I'm getting this exception every day after successful updates:

```
2020-10-15 00:00:29 : DEBUG : scanner : checking object web_mysql
2020-10-15 00:00:29 : DEBUG : service : mysql:5.7
2020-10-15 00:00:29 : DEBUG : abstract : Checking tag: mysql:5.7
2020-10-15 00:00:29 : DEBUG : auth : Looking for auth config
2020-10-15 00:00:29 : DEBUG : auth : No auth config in memory - loading from filesystem
2020-10-15 00:00:29 : DEBUG : config : Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2020-10-15 00:00:29 : DEBUG : config : No config file found
2020-10-15 00:00:29 : DEBUG : auth : Looking for auth entry for 'docker.io'
2020-10-15 00:00:29 : DEBUG : auth : No entry found
2020-10-15 00:00:29 : DEBUG : auth : No auth config found
2020-10-15 00:00:30 : DEBUG : connectionpool : http://localhost:None "POST /v1.35/images/create?tag=5.7&fromImage=mysql HTTP/1.1" 200 None
2020-10-15 00:00:31 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/mysql:5.7/json HTTP/1.1" 404 65
2020-10-15 00:00:31 : ERROR : base : Job "Cron container update for unix://var/run/docker.sock (trigger: cron[month='*', day='*', day_of_week='*', hour='0', minute='0'], next run at: 2020-10-16 00:00:00 CEST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/dockupdater/lib/scanner.py", line 124, in update
    if container_or_service.has_new_version():
  File "/usr/local/lib/python3.7/site-packages/dockupdater/update/service.py", line 108, in has_new_version
    latest_sha = self._get_digest(latest_image)
  File "/usr/local/lib/python3.7/site-packages/dockupdater/update/service.py", line 121, in _get_digest
    digest = image.attrs.get(
AttributeError: 'NoneType' object has no attribute 'attrs'
```

**Comment by mathcantin** [comment]
Which version is your docker?

**Comment by brightdroid** [comment]
I'm running docker 19.03.13 in swarm mode in a three node cluster.
