### ISSUE TITLE
my docker compose file fails

### ISSUE THREAD

**Issue by jboesh** [dockupdater/dockupdater#39]
Hi, I am trying to use the following docker compose file but it fails due to the following error:

`During handling of the above exception, another exception occurred:                                                     
                                                                                                                        
Traceback (most recent call last):                                                                                      
  File "/usr/local/bin/entrypoint", line 7, in <module>                                                                 
    main()                                                                                                              
  File "/usr/local/lib/python3.9/site-packages/dockupdater/dockupdater.py", line 248, in main  
    cli()                                                                                                               
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__                                    
    return self.main(*args, **kwargs)                                                                                   
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main                                        
    rv = self.invoke(ctx)                                                                                               
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke                                     
    return ctx.invoke(self.callback, **ctx.params)                                                                      
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke                                      
    return callback(*args, **kwargs)                                                                                    
  File "/usr/local/lib/python3.9/site-packages/dockupdater/dockupdater.py", line 195, in cli                            
    docker = Docker(socket, config, notification_manager)                                                               
  File "/usr/local/lib/python3.9/site-packages/dockupdater/lib/dockerclient.py", line 16, in __init__                   
    self.client = self.connect()                                                                                        
  File "/usr/local/lib/python3.9/site-packages/dockupdater/lib/dockerclient.py", line 54, in connect                    
    client = DockerClient(base_url=self.socket)                                                                         
  File "/usr/local/lib/python3.9/site-packages/docker/client.py", line 40, in __init__                                  
    self.api = APIClient(*args, **kwargs)                                                                               
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 188, in __init__                             
    self._version = self._retrieve_server_version()                                                                     
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 212, in _retrieve_server_version             
    raise DockerException(                                                                                              
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No
 such file or directory')) `

I have read the documentation, what am I missing?

**Comment by zaggash** [comment]
Hi @jboesh.

It looks like your compose file is missing an important bit, the **docker socket**.

You should add the following lines in your file:
```
volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```

I think the NOTIFIER is almost good.
But from the [apprise documentation](https://github.com/caronc/apprise/wiki/Notify_email), what you are calling `thesender` is actually your `userid`.  
`mailto://{userid}:{password}@gmail.com`
